### ISSUE TITLE
Can't equip/unequip via GUI

### ISSUE THREAD

**Issue by hakanct** [Tiviacz1337/Travelers-Backpack#1023]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Fabric 1.21-10.0.7

1. Describe the bug 
In backpack's GUI I can see equip and unequip buttons but they are not functional. But Shift+RMB equip works.

2. Write steps to reproduce the bug
Open backpack GUI with B if equipped, RMB if not equipped. Click equip/unequip button and it doesn't work.

3. What is expected behaviour 
Equip or unequip when clicked to button.

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
Is there a chance you use trinkets/accessories integration?

**Comment by MartynHollandNL** [comment]
i dont, this is my current mod list:
https://i.imgur.com/WTteVP0.png

**Comment by PurpleSk1ttlez** [comment]
> Is there a chance you use trinkets/accessories integration?

Hi, I have a similar issue. I am using trinkets, the latest version (3.10.0). The backpack says "integration enabled - put backpack in back slot" but clicking it does nothing. Same for removal. This happens every time.

**Comment by Tiviacz1337** [comment]
**Remember to not put any travelersbackpack in back slot before you do that, because it'll remove your current backpack.**
Okay, if you can open backpack, but do not have backpack in back slot you have to do the following thing:
Please go to ESC -> Mods -> find Traveler's Backpack -> click config. Then go to Common -> Backpack settings -> find trinketsIntegration and set to **OFF** (should be at the end of the site). Go back to your game and you can use button to unequip backpack again.

**Comment by PurpleSk1ttlez** [comment]
> **Remember to not put any travelersbackpack in back slot before you do that, because it'll remove your current backpack.** Okay, if you can open backpack, but do not have backpack in back slot you have to do the following thing: Please go to ESC -> Mods -> find Traveler's Backpack -> click config. Then go to Common -> Backpack settings -> find trinketsIntegration and set to **OFF** (should be at the end of the site). Go back to your game and you can use button to unequip backpack again.

I can put it in the back slot but only manually through the inventory. Is this the intended function? Or should the button in the backpack inventory still work? 
When I turn off the trinkets integration, the back slot no longer works.

**Comment by Tiviacz1337** [comment]
If integration is enabled, the button won’t work because you have to place the backpack in the back slot (due to the addition of trinkets). Yes, this is the intended behavior, buttons just show the tooltip to tell player that it has to be placed in back slot

The button will work if you disable the trinkets integration - this means you need to equip the backpack as if trinkets weren’t installed. So, open the backpack inventory and use the button to equip/unequip.

If you have any other questions feel free to ask

**Comment by PurpleSk1ttlez** [comment]
> If integration is enabled, the button won’t work because you have to place the backpack in the back slot (due to the addition of trinkets). Yes, this is the intended behavior, buttons just show the tooltip to tell player that it has to be placed in back slot
> 
> The button will work if you disable the trinkets integration - this means you need to equip the backpack as if trinkets weren’t installed. So, open the backpack inventory and use the button to equip/unequip.
> 
> If you have any other questions feel free to ask

Thank you for explaining!
