### ISSUE TITLE
"target io.wispforest.accessories.impl.AccessoriesEventHandler was not found" for the mod travelersbackpack in Aternos server

### ISSUE THREAD

**Issue by LeGuerrierGorillo** [Tiviacz1337/Travelers-Backpack#1031]
Version 1.20.1 mod loader 0.16.5 in the last verrsion of the mod.
I foun another bug withthe last update of the mod who said in Aternos console server: 
[main/WARN]: Error loading class: io/wispforest/accessories/impl/AccessoriesEventHandler (java.lang.ClassNotFoundException: io/wispforest/accessories/impl/AccessoriesEventHandler)
[main/WARN]:</span> @Mixin target io.wispforest.accessories.impl.AccessoriesEventHandler was not found travelersbackpack.mixins.json:AccessoriesEventHandlerMixin from mod travelersbackpack
Can you try to find a way to fix it please?
![image](https://github.com/user-attachments/assets/ea8f2990-113d-4baa-ba55-7cdb27365805)

**Comment by Tiviacz1337** [comment]
Traveler's Backpack applies mixin if accessories is installed for 1.20.1 to prevent duplication bug (theres no other way than making a mixin on 1.20.1), it seems like you dont have accessories installed and that's why it throws this warning. This is just a warning, it won't cause any issues just ignore it
