### ISSUE TITLE
(still) Compatibility Issues with Aether Mod and Trinkets

### ISSUE THREAD

**Issue by aidan-walden** [Tiviacz1337/Travelers-Backpack#1097]
Continuation of #1090 

Issue is still present in Travelers Backpack version 10.1.5. All other mods up to date.
Trinkets version 3.10.0
Aether version 1.5.1-beta5

**Comment by Tiviacz1337** [comment]
Installing Aether automatically installs Accessories. Accessories and Trinkets are two different mods that have the same functionality. In order for Traveler's Backpack integration to work correctly it uses one mod to integrate with at the time. 
Accessories is the first mod that Traveler's Backpack tries to integrate with, because of trinkets layer (so if accessories and trinkets is installed - it might not be trinkets but trinkets layer (made by accessories dev), that's why it integrates with accessories)
If only Trinkets was installed it would integrate with Trinkets. 

The solution: just use accessories back slot instead. There's no way to fix it at the moment, I do not support using both mods at the same time and I'd suggest to just not use Trinkets in this case to avoid bugs.
