### ISSUE TITLE
Game crashes on left clicking the bag

### ISSUE THREAD

**Issue by tkuye** [Tiviacz1337/Travelers-Backpack#207]
While playing on a server, and after I died and respawned, the backpack was sitting on the ground, and when I right-clicked it, it was fine, however; when I left clicked it, the game would crash. I tried to return to the game and retry however the same thing continued to occur. I attached a video of what would happen when I tried to left click.

https://user-images.githubusercontent.com/72341152/103401022-88159400-4b04-11eb-9899-cd3de369e932.mp4

Thanks!

**Comment by Tiviacz1337** [comment]
Can you send crash log?

**Comment by bessiq** [comment]
I have a similar issue, but it happens when I try to place the backpack on the ground. Here is the log:

[crash-2020-12-29_17.22.17-client.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/5757937/crash-2020-12-29_17.22.17-client.txt)

Seems to be a compatibility issue with the Fairy Lights mod - in my case at least. I disabled Fairy Lights and was able to place and pick up the backpack without crashing.

**Comment by tkuye** [comment]
Here's the crash log:
[crash-2020-12-31_01.15.01-client.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/5758253/crash-2020-12-31_01.15.01-client.txt)

**Comment by Tiviacz1337** [comment]
Update to 5.3.3
