### ISSUE TITLE
Items disappear from the Backpack

### ISSUE THREAD

**Issue by Naelson27** [Tiviacz1337/Travelers-Backpack#233]
I was playing with some mods and added this mod, but, when i stack some of the items in, they disappear 

Example : I put one plank in the backpack, but if i stack another with it, the first will disappear and will be just one plank.

**Comment by Tiviacz1337** [comment]
Can you record video?

**Comment by Naelson27** [comment]
https://www.youtube.com/watch?v=S3zyIt6kFf0 

Here's the video... And i use 1.16.4 (also sorry for the lag in the record, i dont have a good computer for that)

**Comment by Chizurin** [comment]
I have the same issue. It occurs when you quick stack an item in your inventory into an item already in the backpack. It causes the quick stacked items to disappear. For example, if you already have the 1 dirt in your backpack and you quick stack 20 dirt into your backpack and then close the backpack, the 20 dirt disappears. This happens inconsistently and the only way I found a way around this was by taking the items already in the backpack and stacking it into my inventory before putting all of it into my backpack. You can quick stack how many items. It also happens when you right click one single item that already exists in the backpack, causing the one item you just put into the backpack to disappear as soon as you close and open your backpack again. 

This happened to me on the latest version of the mod on version 1.16.4. I hope this gets fixed somehow because I really enjoy using the mod.

**Comment by Tiviacz1337** [comment]
Latest means?

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3171745
