### ISSUE TITLE
Backpack Abilities Not Working

### ISSUE THREAD

**Issue by WeirdoThat** [Tiviacz1337/Travelers-Backpack#459]
**Describe the bug**
No matter what backpack you equip, the abilities do not work/take effect.

**To Reproduce**
1. Make a standard traveler's backpack
2. Craft it into a backpack that's supposed to have an ability
3. Equip the backpack

**Expected behavior**
I expected to equip a blaze backpack and no longer die to being thrown off of cliffs by monsters. It was quite not the case.

**Required informations (please complete the following information):**
 - Mod version: 1.19 - 8.0.2
- Mod Loader: Fabric

**Additional context**
Not much other than it's part of the Medieval MC modpack, which seems to have a few issues in general.

**Comment by Tiviacz1337** [comment]
To enable backpack ability, you have to switch ability slider to enabled. The issue is that Medieval MC modpack uses custom gui texture for my backpack. The texture in modpack is not updated and therefore button is not visible. Button still can be accessed if backpack has ability - slider is located under left bucket out slot. To have slider visible you have to disable one of excalibur resourcepacks (Excalibur mod support as I remember) You can report it to resourcepack makers or Medieval MC devs to update the resourcepack texture.
