### ISSUE TITLE
In multiplayer, only the newest backpack can craft

### ISSUE THREAD

**Issue by ILikePizza555** [Tiviacz1337/Travelers-Backpack#728]
# ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Fabric - v1.20.1-9.15, Multiplayer

# Describe the bug 

What it says on the tin: In multiplayer, only the newest backpack can craft. If a player crafts a backpack, that's the only backpack on the server with crafting ability. If a zombie spawns wearing a backpack and drops it, that becomes the  only backpack on the server with crafting ability. If a player upgrades a backpack that's the only backpack with crafting ability.

# Write steps to reproduce the bug

1. Create a backpack on a multiplayer server.
2. Try to craft, observe that it works
3. Create a new backpack on that server
4. Try to craft with the old backpack, observe that nothing appears in the crafting result
5. Try to craft with the new backpack, observe that it works

# What is expected behaviour 

I think all players should be able to craft.

**Comment by octylFractal** [comment]
This is not strictly correct, any backpack can work at any time, but the result slot is disabled under incorrect circumstances.

https://github.com/Tiviacz1337/Travelers-Backpack/blob/89aa1b00f5d9cf382e021afc468e274cce8e1cd2/src/main/java/com/tiviacz/travelersbackpack/inventory/Tiers.java#L105-L108 was updated to use these tiny slot numbers, instead of the correct calculation, which would be a slightly adjusted version of what is commented out. The effect is that putting an item in slot 2 or 3 of the backpack will disable the result slot, instead of the right bucket slots as intended.

**Comment by Tiviacz1337** [comment]
> This is not strictly correct, any backpack can work at any time, but the result slot is disabled under incorrect circumstances.
> 
> https://github.com/Tiviacz1337/Travelers-Backpack/blob/89aa1b00f5d9cf382e021afc468e274cce8e1cd2/src/main/java/com/tiviacz/travelersbackpack/inventory/Tiers.java#L105-L108
> 
> was updated to use these tiny slot numbers, instead of the correct calculation, which would be a slightly adjusted version of what is commented out. The effect is that putting an item in slot 2 or 3 of the backpack will disable the result slot, instead of the right bucket slots as intended.

Thank you for your comment, I forgot to edit result slot code while I was moving bucket slots out of saveable backpack inventory, fix should be available today

**Comment by Tiviacz1337** [comment]
fixed for fabric: 
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files
https://modrinth.com/mod/travelersbackpack/versions

**Comment by Tiviacz1337** [comment]
Fixed for forge: 
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files
https://modrinth.com/mod/travelersbackpack/versions
