### ISSUE TITLE
Unable to cycle between tools

### ISSUE THREAD

**Issue by JBJones42** [Tiviacz1337/Travelers-Backpack#732]
Fabric, 1.19.2-8.2.30

When I use the keybind + scroll with tools in the green slots and a tool in my hand, it doesn't swap the items, it just scrolls through my hot bar. I'm holding the keybind and scrolling at the same time. I went to the config file to try and disable the scrolling and just have it be a keybind swap, but the only option I can see is to allow tools to swap with keybind + scroll, or no swapping at all.

Have the basic backpack equipped, put tools in the two green slots and one tool in your hot bar, attempt to hold keybind + scroll.

Expected behavior is for it to cycle the tools.

**Comment by JBJones42** [comment]
Okay, so I tried doing other keys for the cycle bind, and those ended up working fine without needing to scroll, but it seems like just the 'G' key doesn't work as a bind for some reason? It's not bound to anything else in my settings so surely it can't be an action conflict, but I have no idea what else could make it not work.

**Comment by McfarlaneRob** [comment]
Have had a similar issue when playing the "Prominence II" modpack on 1.20.1
Had the change the keybind due to conflicts, and it allows to cycle through the tools that are stored by pressing the key, but not by holding and scrolling.
Another issue i'm having is that I can't remove tools/weapons from the backpack, as it only allows me to cycle from an occupied toolbar slot.
Not sure if this is intended behaviour.

**Comment by Tiviacz1337** [comment]
Added ability to use scroll on fabric, I just didn't know how to do it in that time, will be available in the next update

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all
https://modrinth.com/mod/travelersbackpack/versions
