### ISSUE TITLE
Game crashes when trying to open a backpack.

### ISSUE THREAD

**Issue by GameOnne** [Tiviacz1337/Travelers-Backpack#927]
Version: 1.19.2
Modloader: Fabric 0.15.11
Mod version: 8.2.37

1. The game crashes whenever I try to open a backpack.

2. Right click a backpack.

3. I'm not an expert but I believe that it should open.

[latest.log](https://github.com/user-attachments/files/15849620/latest.log)

**Comment by Tiviacz1337** [comment]
I'll take a look at it today or tomorrow

**Comment by erik-petrov** [comment]
[link](https://cdn.discordapp.com/attachments/724971015637303306/1249808848051634266/log-22-32.txt?ex=666f3e31&is=666decb1&hm=35ada36905991098d56e27ff0b73e7a2bee3bcf5e30af096bdcb40308ca709cf&) to logs with the same problem on the discord server(with MixinTrace and StackDeobfuscator)
as mentioned by @nerjalnosk on discord and by turning off mods, its probably caused by JEI

**Comment by GameOnne** [comment]
Yup, it was caused by JEI. Switching to REI solved this issue. Thanks!
