### ISSUE TITLE
Cannot equip backpacks at all, and they disappear

### ISSUE THREAD

**Issue by samuiless** [Tiviacz1337/Travelers-Backpack#949]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Forge 1.19.2 43.4.0 
Mod version 8.2.40

1. Describe the bug 
I had the main backpack equipped on my back and then while mining using baritone i equipped another backpack. out of a sudden my pickaxe disappeared i checked all my inventory slots and nothing. then i tried to equip one of the backpacks and it disappeared. then i tried to reequip my main one and it vanished 

2. Write steps to reproduce the bug
while using baritone mining command, immediately try to manually equip a 2nd backpack while already having one on your back.

3. What is expected behaviour 
the backpack should disappear and any further backpacks that you want to equip will be lost into the void

4. Screenshots (If applicable)
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/174901783/c4a13669-0f04-495d-9024-c97a6fa9a45c)

**Comment by samuiless** [comment]
issue can be fixed due to some reason where in the player Data DAT file when you check the traveler's backpack it will say the last item that was held. All you have to do is delete the traveler's backpack class in the DAT file under a parent node that says forge

**Comment by PaterFrog** [comment]
I noticed the same today after crafting and equipping another mod's backpack (Create: Storage, in this case).
I'd equipped that backpack, put my Traveler's backpack on the ground and shift-clicked it to equip it out of force of habit and it deleted itself along with all the items inside.

It seemed as though the logic to equip the backpack simply runs, fails to check if something is already in the Trinkets's back slot, doesn't check whether the backpack was successfully equipped, and then deletes the backpack from the ground as though it had been successfully equipped, because the backpack didn't drop as an inventory item either.

**Comment by Tiviacz1337** [comment]
what is baritone

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20
Added check for fabric to prevent equipping backpack if back slot is taken by other item
