### ISSUE TITLE
Can't switch modes on my hose

### ISSUE THREAD

**Issue by tatertotman33** [Tiviacz1337/Travelers-Backpack#990]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
fabric 1.21

1. Describe the bug 

Cannot switch hose modes any more

2. Write steps to reproduce the bug

Not sure I have a decent amount of quality of life mods but nothing that actually adds different weapons items or anything to the game not too sure how it happens it just does

3. What is expected behaviour 
when I use my extra mouse button then the scroll button its supposed to switch modes it shows the animation of it changing but it doesnt change the name or the model of the hose changing like how it does when you switch it

4. Screenshots (If applicable)

**Comment by Joeyneko64** [comment]
this bug also happen to me and what i think how the bug happen is when I'm unequip and re-equip my backpack and the try to use scroll wheel to change the mode of the hose the bug happen. So the only way to fix this bug is to unequip and re-equip the back pack and then right click when I'm holding the hose first and don't use the scroll wheel first or the bug will happen again

**Comment by Tiviacz1337** [comment]
https://github.com/Tiviacz1337/Travelers-Backpack/wiki/How-to-use-Hose
